## Copyright 2023 The MathWorks, Inc.

name: 'polyspace-bug-finder'
author: 'MathWorks'
description: 'Run a Polyspace Bug Finder Server analysis, save results to a SARIF file, and optionally upload to Polyspace Access.'
inputs:
    polyspace-installation-folder:
      description: 'Polyspace installation folder path. 
      If you add the path of the Polyspace executables to your PATH environment variable, you do not need to specify the installation folder path.'
      required: false
    working-directory:
      description: 'Working directory folder path. Specify the path relative to GITHUB_WORKSPACE.
       If you do not specify a working directory, Polyspace uses GITHUB_WORKSPACE.'
      required: false

## Configuration and Analysis Options
    compilation-database-file:
      description: 'Compilation database file path, e.g. compile_commands.json.
       This input is not compatible with the build-command input.'
      required: false
    build-command:
      description: 'Build command you specify to perform a full build, e.g. make -B.
       This input is not compatible with the compilation-database-file input.'
      required: false
    checkers-file:
      description: 'Checker activation file path.'
      required: false
    results-dir:
      description: 'Folder path where generated results are stored.'
      required: false
      default: 'ps_results'
    options-file:
      description: 'Polyspace analysis options file path.
       If you use multiple options files, specify the path of one options file that references all the other options files.'
      required: false

## SARIF Export
    sarif-file:
      description: 'Name of the generated SARIF file.'
      default: 'results.sarif'
      required: true

## Upload to Polyspace Access
    api-key:
      description: 'The API Key used to log into Polyspace Access.'
      required: false
    host:
      description: 'Fully qualified host name of the machine that hosts Polyspace Access.'
      required: false
    protocol:
      description: 'HTTP protocol used by Polyspace Access to communicate with client machines, e.g http or https.'
      required: false
    port:
      description: 'Port number used by Polyspace Access to communicate with client machines.'
      required: false
    project-name:
      description: 'Name of the uploaded results in Polyspace Access project explorer.'
      required: false
    parent-project:
      description: 'Name of the project folder under which the uploaded results are stored in Polyspace Access project explorer.'
      required: false

## Extra options
    configure-extra-options:
      description: 'Pass additional options to the polyspace-configure executable.'
      required: false
    bugfinder-extra-options:
      description: 'Pass additional options to the polyspace-bug-finder-server executable.'
      required: false
    access-extra-options:
      description: 'Pass additional options to the polyspace-access executable.'
      required: false

## Diff analysis
    push-reduced-analysis:
      description: 'Analyze files only if they are in the list of changed files pushed to the repository and 
      the file extensions match one of the extensions specified with source-file-allow-list.'
      type: boolean
      default: false

## Pull-request specifics
    pull-request-reduced-analysis:
      description: 'Analyze files only if they are in the list of changed files of a pull request and 
      the file extensions match one of the extensions specified with source-file-allow-list.'
      type: boolean
      default: false
    pull-request-number: 
      description: 'Pull request number that the analysis runs on if you set pull-request-reduced-analysis to true
      and run this action in a pull request context. If you do not specify a pull request number, the action uses the default value.'
      default: ${{ github.event.pull_request.number }}
    github-token:
      description: 'Access token generated by Github for authentication in the workflow job. Polyspace uses the token
      to authenticate when adding annotations to a commit.'
      default: ${{ github.token }}
      required: true
    source-file-allow-list:
      description: 'Comma separated list of file extensions. Polyspace only analyzes files with the specified extensions.
       By default the list includes the extensions of only c and c++ sources and header files.'
      default: '.cpp,.cxx.hpp,.c,.h,.cc,.hh'

runs:
  using: 'node16'
  main: 'dist/polyspaceBugFinder/index.js'
